server:
  port: 8010
info:
  artifactId: @project.artifactId@
user:
  userServiceUrl: http://localhost:8000/
spring:
  application:
    name: microservice-consumer-move
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true