server:
  port: 8010
spring:
  application:
    name: microservice-consumer-move
microservice-provider-user:
  ribbon:
    listOfServers: localhost:8000,localhost:8001
#饥饿加载配置
ribbon:
  eager-load:
    enabled: true
    clients: client1,client2