server:
  port: 8000
spring:
  application:
    name: microservice-provider-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie_data
    username: root
    password: 1234
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
info:
  artifactId: @project.artifactId@
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      my-metadata: 我的自定义元数据