server:
  port: 8000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie_data
    username: root
    password: 1234
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
info:
  artifactId: @project.artifactId@