server:
  port: 8761
spring:
  application:
    name: microservice-discovery-eureka
  security:
    user:
      name: user
      password: 123
eureka:
  client:
    service-url:
      defaultZone: http://user:123@localhost:8761/eureka/