server:
  port: 8000
spring:
  datasource:
    url: jdbc:sqlserver://10.0.0.1:1433;databasename=jk_database2
    username: hbsc321e!@#!ASA
    password: ASDFJKH1236@#$!#
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
mybatis:
  type-aliases-package: com.wpy.mybatis.springbootmybatis.model
  mapper-locations: classpath:mapper/*.xml